packages:
  - ./non-react
  - ./react-based/*

onlyBuiltDependencies:
  - sharp

overrides:
  '@types/node': ^24.10.4
  "@types/react": "^19.2.2"
  "@types/react-dom": "^19.2.2"
  # eslint: ">=10.0.0"
  # '@eslint/js': ">=10.0.0"
  '@stylistic/eslint-plugin': '>=5.0.0'
  '@eslint/eslintrc>ajv': ^6.12.4
  ajv@<8.18.0: '>=8.18.0'
  eslint>ajv: ^6.12.4
