packages:
  - ./non-react
  - ./react-based/*

onlyBuiltDependencies:
  - sharp

overrides:
  "@types/react": "19.2.2"
  "@types/react-dom": "19.2.2"
  eslint@=9.39.0: ">=10.0.0"
  '@eslint/js@=9.39.0': ">=10.0.0"
